<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="conversationalGame" nsURI="http://www.example.org/var" nsPrefix="conversationalGame">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Player" lowerBound="1"
        eType="#//Player" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SpawnRoom" lowerBound="1"
        eType="#//Room"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RoomList" lowerBound="1"
        upperBound="-1" eType="#//Room" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TriggerList" upperBound="-1"
        eType="#//Trigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Greeting" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Character">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Inventory" upperBound="-1"
        eType="#//Item" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Stats" upperBound="-1"
        eType="#//Stat" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Dead" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Actions" ordered="false"
        upperBound="-1" eType="#//CharacterAction">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player" eSuperTypes="#//Character">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CurrentRoom" lowerBound="1"
        eType="#//Room"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Npc" eSuperTypes="#//Character">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FirstEncounterTrigger"
        eType="#//RoomTrigger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="idUniqueRoom NoSelfNavigation goAndBack atLeastOne"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="idUniqueRoom" value="&#xA;&#x9;&#x9;&#x9;Room.allInstances()->isUnique(Id)&#xA;&#x9;&#x9;"/>
      <details key="NoSelfNavigation" value="&#xA;&#x9;&#x9;&#x9;let ngo: Boolean = North->collect(d | d.oclAsType(Door).Next.Id)->select(i | i = self.Id)->isEmpty() in&#xA;&#x9;&#x9;&#x9;let sgo: Boolean = South->collect(d | d.oclAsType(Door).Next.Id)->select(i | i = self.Id)->isEmpty() in&#xA;&#x9;&#x9;&#x9;let ego: Boolean = East->collect(d | d.oclAsType(Door).Next.Id)->select(i | i = self.Id)->isEmpty() in&#xA;&#x9;&#x9;&#x9;let wgo: Boolean = West->collect(d | d.oclAsType(Door).Next.Id)->select(i | i = self.Id)->isEmpty() in&#xA;&#x9;&#x9;&#x9;ngo and sgo and ego and wgo"/>
      <details key="goAndBack" value="&#xA;&#x9;&#x9;&#x9;let ngoback: Boolean = North->collect(d | d.oclAsType(Door).Next.South.Next.Id)->select(i | i &lt;> self.Id)->isEmpty() in&#xA;&#x9;&#x9;&#x9;let sgoback: Boolean = South->collect(d | d.oclAsType(Door).Next.North.Next.Id)->select(i | i &lt;> self.Id)->isEmpty() in&#xA;&#x9;&#x9;&#x9;let egoback: Boolean = East->collect(d | d.oclAsType(Door).Next.West.Next.Id)->select(i | i &lt;> self.Id)->isEmpty() in&#xA;&#x9;&#x9;&#x9;let wgoback: Boolean = West->collect(d | d.oclAsType(Door).Next.East.Next.Id)->select(i | i &lt;> self.Id)->isEmpty() in&#xA;&#x9;&#x9;&#x9;ngoback and sgoback and egoback and wgoback"/>
      <details key="atLeastOne" value="&#xA;&#x9;&#x9;&#x9;let ndoor: Integer = North->collect(d | d.oclAsType(Door))->size() in&#xA;&#x9;&#x9;&#x9;let sdoor: Integer = South->collect(d | d.oclAsType(Door))->size() in&#xA;&#x9;&#x9;&#x9;let edoor: Integer = East->collect(d | d.oclAsType(Door))->size() in&#xA;&#x9;&#x9;&#x9;let wdoor: Integer = West->collect(d | d.oclAsType(Door))->size() in&#xA;&#x9;&#x9;&#x9;ndoor + sdoor + edoor + wdoor >= 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="North" eType="#//Door"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="South" eType="#//Door"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="East" eType="#//Door" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="West" eType="#//Door" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Items" upperBound="-1"
        eType="#//Item" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Npcs" upperBound="-1" eType="#//Npc"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="idUniqueItem"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="idUniqueItem" value="&#xA;&#x9;&#x9;&#x9;Item.allInstances()->isUnique(Id)&#xA;&#x9;&#x9;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Actions" upperBound="-1"
        eType="#//ItemAction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Consequence" eType="#//Consequence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CharacterAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Consequence" eType="#//Consequence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatConsequence" eSuperTypes="#//Consequence">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Stat" lowerBound="1" eType="#//Stat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Character" lowerBound="1"
        eType="#//Character"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConsequenceGiveItem" eSuperTypes="#//Consequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="NewItems" upperBound="-1"
        eType="#//Item"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Character" lowerBound="1"
        eType="#//Character"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConsequenceSpawnItem" eSuperTypes="#//Consequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="NewItems" upperBound="-1"
        eType="#//Item"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Room" lowerBound="1" eType="#//Room"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoomConsequence" eSuperTypes="#//Consequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Door" eType="#//Door"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Door">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="idUniqueDoor"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="idUniqueDoor" value="&#xA;&#x9;&#x9;&#x9;Door.allInstances()->isUnique(Id)&#xA;&#x9;&#x9;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Open" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Next" lowerBound="1" eType="#//Room"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnswerConsequence" eSuperTypes="#//Consequence">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Question" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Answer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="idUniqueDoor"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="idUniqueDoor" value="&#xA;&#x9;&#x9;&#x9;Door.allInstances()->isUnique(Id)&#xA;&#x9;&#x9;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Triggered" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EndGame" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Consequences" ordered="false"
        upperBound="-1" eType="#//Consequence">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoomTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Room" eType="#//Room"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Item" eType="#//Item"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NpcTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Npc" eType="#//Npc"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlayerTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Player" eType="#//Player"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Consequence">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Consequence" eType="#//Consequence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ItemAction" eType="#//ItemAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CharacterAction" eType="#//CharacterAction"/>
  </eClassifiers>
</ecore:EPackage>
